### PR TITLE
Add mongo-go-driver

### PR DESCRIPTION
**Pull request by marhaupe**
This is an official driver from the mongo organisation. It recently reached v.1.0.0 and is currently a viable driver, especially since mgo has been declared as unmaintained.

Please check if what you want to add to `awesome-go-storage` list meets [quality standards](https://github.com/gostor/awesome-go-storage/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo:  https://github.com/mongodb/mongo-go-driver
- godoc.org: https://godoc.org/go.mongodb.org/mongo-driver/mongo
- goreportcard.com: https://goreportcard.com/report/go.mongodb.org/mongo-driver
- coverage service link (gocover, coveralls etc.): not available

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have *not* added coverage service link to the repo and to my pull request, because there isn't one available.
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/gostor/awesome-go-storage/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/gostor/awesome-go-storage/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by Oppodelldog** [comment]
We could additionally mention that mgo is unmaintained.

**Comment by marhaupe** [comment]
Do you mean that I should add a commit with that change or are you just saying that you're agreeing with this pull request?

**Comment by Oppodelldog** [comment]
Both, I agree and would suggest to update the old driver with the same change.
As we can see from the very top of the page mgo is not maintained anymore.
https://github.com/go-mgo/mgo

**Comment by carmark** [comment]
Thanks @marhaupe

**Pull request merged**
